[package]
name = "advent_2020"
version = "0.1.0"
authors = ["Marco Vellinga <marco@vellinga.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
